/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Frequency = IDL.Variant({
  'occasionally' : IDL.Null,
  'daily' : IDL.Null,
  'multipleTimesDaily' : IDL.Null,
  'biweekly' : IDL.Null,
  'weekly' : IDL.Null,
});
export const CustomerInfo = IDL.Record({
  'visitFrequency' : Frequency,
  'newsletterOptIn' : IDL.Bool,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'favoriteCoffee' : IDL.Text,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomers' : IDL.Func([], [IDL.Vec(CustomerInfo)], ['query']),
  'getNewsletterSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerCustomer' : IDL.Func([CustomerInfo], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'subscribeToNewsletter' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Frequency = IDL.Variant({
    'occasionally' : IDL.Null,
    'daily' : IDL.Null,
    'multipleTimesDaily' : IDL.Null,
    'biweekly' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const CustomerInfo = IDL.Record({
    'visitFrequency' : Frequency,
    'newsletterOptIn' : IDL.Bool,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'favoriteCoffee' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomers' : IDL.Func([], [IDL.Vec(CustomerInfo)], ['query']),
    'getNewsletterSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerCustomer' : IDL.Func([CustomerInfo], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'subscribeToNewsletter' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };